<a href="https://colab.research.google.com/github/Innovatewithapple/Pipelines-CrossValidation-Regularisation/blob/main/ClassificationPipeline.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [16]:
# basic
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# model + preprocessing
from sklearn.model_selection import train_test_split,cross_val_score,GridSearchCV
from sklearn.preprocessing import StandardScaler,OneHotEncoder,LabelEncoder
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer

#model
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier

In [10]:
df = pd.read_csv('/content/student_mental_health_burnout.csv')
df.sample(10)

        student_id  age  gender  ...  cgpa internet_quality  burnout_level
63592       163593   18    Male  ...  9.99          Average            Low
27566       127567   25    Male  ...  4.97             Poor            Low
13345       113346   19  Female  ...  4.75             Good            Low
113408      213409   19  Female  ...  9.50          Average         Medium
32682       132683   25  Female  ...  9.33             Poor         Medium
23143       123144   23  Female  ...  4.74          Average           High
68500       168501   20  Female  ...  4.56             Poor            Low
102614      202615   21    Male  ...  5.70             Good           High
85582       185583   23   Other  ...  6.02             Poor           High
86379       186380   21   Other  ...  6.76          Average            Low

[10 rows x 20 columns]

In [4]:
df.describe()

          student_id            age  ...  attendance_percentage           cgpa
count  150000.000000  150000.000000  ...          150000.000000  150000.000000
mean   175000.500000      21.000380  ...              75.009528       6.997389
std     43301.414527       2.581216  ...              14.409510       1.732180
min    100001.000000      17.000000  ...              50.000000       4.000000
25%    137500.750000      19.000000  ...              62.500000       5.500000
50%    175000.500000      21.000000  ...              75.000000       6.990000
75%    212500.250000      23.000000  ...              87.500000       8.500000
max    250000.000000      25.000000  ...             100.000000      10.000000

[8 rows x 13 columns]

In [11]:
df.sample(10)

        student_id  age  gender  ...  cgpa internet_quality  burnout_level
144438      244439   18   Other  ...  8.66             Good            Low
99686       199687   23    Male  ...  5.16             Poor           High
49789       149790   17  Female  ...  7.03             Good         Medium
7867        107868   22  Female  ...  6.35          Average            Low
20725       120726   17   Other  ...  4.65             Good           High
47927       147928   21    Male  ...  9.54          Average            Low
78754       178755   18    Male  ...  7.79          Average            Low
12143       112144   20   Other  ...  9.28             Poor            Low
100534      200535   20   Other  ...  9.97          Average            Low
113715      213716   23  Female  ...  5.94          Average         Medium

[10 rows x 20 columns]

In [12]:
x = df.drop(columns=['student_id','course'])
y = df['burnout_level']

In [14]:
labelencode = LabelEncoder()
y = labelencode.fit_transform(y)

In [15]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3,random_state=42)

In [20]:
#transorm
scalingColumns = ['age','daily_study_hours','daily_sleep_hours','screen_time_hours','anxiety_score','depression_score','academic_pressure_score','financial_stress_score','social_support_score','physical_activity_hours','attendance_percentage','cgpa']
encodeColumns = ['gender','year','stress_level','sleep_quality','internet_quality']
preprocessor = ColumnTransformer([
    ('nums',StandardScaler(),scalingColumns),
    ('cat',OneHotEncoder(),encodeColumns)
])

In [21]:
#Logistic
pipeline = Pipeline([
    ('preprocess',preprocessor),
    ('model',LogisticRegression())
])

In [22]:
pipeline.fit(x_train,y_train)

Pipeline(steps=[('preprocess',
                 ColumnTransformer(transformers=[('nums', StandardScaler(),
                                                  ['age', 'daily_study_hours',
                                                   'daily_sleep_hours',
                                                   'screen_time_hours',
                                                   'anxiety_score',
                                                   'depression_score',
                                                   'academic_pressure_score',
                                                   'financial_stress_score',
                                                   'social_support_score',
                                                   'physical_activity_hours',
                                                   'attendance_percentage',
                                                   'cgpa']),
                                                 ('cat', OneHotEncoder(),
                                                  ['gender', 'year',
                                                   'stress_level',
                                                   'sleep_quality',
                                                   'internet_quality'])])),
                ('model', LogisticRegression())])

In [23]:
cross_score = cross_val_score(pipeline,x_train,y_train,cv=5,scoring='f1_weighted')
print(cross_score)

[0.32988589 0.32629949 0.32787962 0.33148229 0.32959371]

In [24]:
cross_score = cross_val_score(pipeline,x_train,y_train,cv=5,scoring='accuracy')
print(cross_score)

[0.33547619 0.331      0.33166667 0.33561905 0.33304762]

In [27]:
# SVM
pipeline_svm = Pipeline([
    ('preprocess',preprocessor),
    ('model',SVC())
])

In [ ]:
pipeline_svm.fit(x_train,y_train)