<a href="https://colab.research.google.com/github/Innovatewithapple/Pipelines-CrossValidation-Regularisation/blob/main/ClusterPPipeline.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.preprocessing import OneHotEncoder,StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.cluster import KMeans, DBSCAN, AgglomerativeClustering
from sklearn.pipeline import Pipeline

from sklearn.metrics import silhouette_score

In [2]:
df = pd.read_csv('/content/store_customers.csv')
df.sample(5)

     CustomerID Gender   Age  Annual Income (k$)  Spending Score (1-100)
38         1038      F  24.0                27.1                    73.0
340        1340      M  28.0                24.9                    59.0
327        1327      M  41.0                63.6                    35.0
497        1497      F  33.0                34.6                    51.0
782        1782      M  75.0               116.0                     1.0

In [9]:
df.isnull().sum()

CustomerID                0
Gender                    3
Age                       6
Annual Income (k$)        4
Spending Score (1-100)    6
dtype: int64

In [10]:
median_age = df['Age'].median()
df['Age'] = df['Age'].fillna(median_age)

In [14]:
median_annual_income = df['Annual Income (k$)'].median()
df['Annual Income (k$)'] = df['Annual Income (k$)'].fillna(median_annual_income)

In [16]:
median_spending_score = df['Spending Score (1-100)'].median()
df['Spending Score (1-100)'] = df['Spending Score (1-100)'].fillna(median_spending_score)

In [17]:
df.isnull().sum()

CustomerID                0
Gender                    3
Age                       0
Annual Income (k$)        0
Spending Score (1-100)    0
dtype: int64

In [18]:
x = df[['Age','Annual Income (k$)','Spending Score (1-100)']]

In [19]:
# split columns for scaling and encoding
nums = ['Age','Age','Annual Income (k$)','Spending Score (1-100)']

In [20]:
preprocessor = ColumnTransformer([
    ("nums",StandardScaler(),nums)
])

In [21]:
#KMeans pipeline
pipeline = Pipeline([
    ('preprocess',preprocessor),
    ('model',KMeans(n_clusters=5,random_state=42))
])

In [22]:
label_kmeans = pipeline.fit_predict(x)

In [40]:
#DBSCAN pipeline
pipeline_dbscan = Pipeline([
    ("preprocess",preprocessor),
    ("model",DBSCAN(eps=0.7,min_samples=5))
])

In [41]:
label_dbscan = pipeline_dbscan.fit_predict(x)

In [42]:
def evlauation(x,labels,name):
  if len(set(labels)) > 1:
    score = silhouette_score(preprocessor.fit_transform(x),labels)
    print(f"{name} silhoutte score is:",score)
  else:
    print(f"{name} failed (single cluster)")

In [43]:
evlauation(x,label_kmeans,"Kmeans")
evlauation(x,label_dbscan,"DBSCAN")

Kmeans silhoutte score is: 0.3400410537346608
DBSCAN silhoutte score is: 0.3569412986693095