<a href="https://colab.research.google.com/github/Innovatewithapple/Pipelines-CrossValidation-Regularisation/blob/main/ClusterPPipeline.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [17]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.preprocessing import OneHotEncoder,StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.cluster import KMeans, DBSCAN, AgglomerativeClustering
from sklearn.pipeline import Pipeline

from sklearn.metrics import silhouette_score

In [41]:
df = pd.read_csv('/content/store_customers.csv')
df.sample(5)

     CustomerID Gender   Age  Annual Income (k$)  Spending Score (1-100)
158        1158      F  25.0                23.7                    65.0
354        1354      M  35.0                51.7                    62.0
886        1886      M  22.0                15.0                    39.0
330        1330      F  35.0                49.3                    62.0
406        1406      M  26.0                32.7                    49.0

In [42]:
df.isnull().sum()

CustomerID                0
Gender                    3
Age                       6
Annual Income (k$)        4
Spending Score (1-100)    6
dtype: int64

In [20]:
median_age = df['Age'].median()
df['Age'] = df['Age'].fillna(median_age)

In [21]:
median_annual_income = df['Annual Income (k$)'].median()
df['Annual Income (k$)'] = df['Annual Income (k$)'].fillna(median_annual_income)

In [22]:
median_spending_score = df['Spending Score (1-100)'].median()
df['Spending Score (1-100)'] = df['Spending Score (1-100)'].fillna(median_spending_score)

In [45]:
df.dropna(inplace=True)

In [46]:
df.isnull().sum()

CustomerID                0
Gender                    0
Age                       0
Annual Income (k$)        0
Spending Score (1-100)    0
dtype: int64

In [47]:
x = df[['Annual Income (k$)','Spending Score (1-100)']]

In [48]:
# split columns for scaling and encoding
nums = ['Annual Income (k$)','Spending Score (1-100)']

In [49]:
preprocessor = ColumnTransformer([
    ("nums",StandardScaler(),nums)
])

In [50]:
#KMeans pipeline
pipeline = Pipeline([
    ('preprocess',preprocessor),
    ('model',KMeans(n_clusters=5,random_state=42))
])

In [51]:
label_kmeans = pipeline.fit_predict(x)

In [52]:
#DBSCAN pipeline
pipeline_dbscan = Pipeline([
    ("preprocess",preprocessor),
    ("model",DBSCAN(eps=0.2,min_samples=2))
])

In [53]:
label_dbscan = pipeline_dbscan.fit_predict(x)

In [54]:
def evlauation(x,labels,name):
  if len(set(labels)) > 1:
    score = silhouette_score(preprocessor.fit_transform(x),labels)
    print(f"{name} silhoutte score is:",score)
  else:
    print(f"{name} failed (single cluster)")

In [55]:
evlauation(x,label_kmeans,"Kmeans")
evlauation(x,label_dbscan,"DBSCAN")

Kmeans silhoutte score is: 0.35374964532033915
DBSCAN silhoutte score is: -0.3304876234189652